CarboBundle\Entity\Hidrato:
    type: entity
    table: hidrato
    repositoryClass: CarboBundle\Repository\HidratoRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        hidratoCarbono:
            type: float
            nullable: false
            length: 255
            options:
                fixed: false
            column: hidrato_carbono
        horasEntreno:
            type: time
            nullable: false
            length: 255
            options:
                fixed: false
            column: horas_entreno
        kmEntreno:
            type: integer
            nullable: true
            length: 255
            options:
                fixed: false
            column: km_entreno
        fechaCreacion:
            type: date
            nullable: false
            length: 255
            options:
                fixed: false
            column: fecha_creacion
        fechaActualizacion:
            type: date
            nullable: true
            length: 255
            options:
                fixed: false
            column: fecha_actualizacion
        ruta:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        peso:
            type: float
            nullable: false
            length: 255
            options:
                fixed: false
    manyToOne:
        user:
            targetEntity: User
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false

    lifecycleCallbacks: {  }
